name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: dcarbone/install-jq-action@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - uses: coactions/setup-xvfb@v1
        with:
          run: pnpm run check

  publish:
    needs: check
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NAME: codelens-golang-navigate-${{ github.ref_name }}.vsix
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run compile
      - uses: HaaLeo/publish-vscode-extension@v2
        id: publish-open-vsx
        with:
          pat: ${{ secrets.TOKEN_OPEN_VSX }}
      - uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.TOKEN_VS_MARKETPLACE }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publish-open-vsx.outputs.vsixPath }}
      - uses: actions/upload-artifact@v5
        with:
          name: ${{ env.NAME }}
          path: ${{ steps.publish-open-vsx.outputs.vsixPath }}
      - run: mv ${{ steps.publish-open-vsx.outputs.vsixPath }} ${{ runner.temp }}/${{ env.NAME }}
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ runner.temp }}/${{ env.NAME }}
